<a href="https://colab.research.google.com/github/pythongeek0408/baby_steps_python/blob/main/n_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Higher dimensional Tensor

In [ ]:
# Eg for 4 dim Tensor
# Number of images in training model - 32
# Image height in pixels -28
# Image width in pixels - 28
# Number of color channels- 3 (RGB)
import torch
images_pt = torch.zeros([32,28,28,3])

In [ ]:
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [ ]:
import numpy as np

In [ ]:
x = np.array([[25],[2],[-3],[-23]])
x

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [ ]:
x.T

array([[ 25,   2,  -3, -23]])

In [ ]:
import torch
Y_pt = torch.tensor([[42,4,7,99],[-99,-3,17,22]])
Y_pt

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [ ]:
Y_pt.shape

torch.Size([2, 4])

In [ ]:
Y_ pt[1,2]

SyntaxError: ignored