<a href="https://colab.research.google.com/github/pythongeek0408/baby_steps_python/blob/main/dot_Product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
import torch

In [ ]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [ ]:
y = np.array([0,1,2])
y

array([0, 1, 2])

In [ ]:
np.dot(x,y)

12

In [ ]:
x_pt = torch.tensor([25,2,5],dtype = torch.float16)
x_pt


tensor([25.,  2.,  5.], dtype=torch.float16)

In [ ]:
y_pt=torch.tensor([0,1,2],dtype = torch.float16)
y_pt

tensor([0., 1., 2.], dtype=torch.float16)

In [ ]:
np.dot(x_pt,y_pt)

12

In [ ]:
torch.dot(x_pt,y_pt) #dot product in pytorch needs float tensors

tensor(12., dtype=torch.float16)

In [ ]:
Y_pt = np.array([[42,4,7,99],[-99,-3,17,22]])
Y_pt
Y_pt.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [ ]:
A_pt = torch.tensor([[25,10],[-2,1]])
A_pt

tensor([[25, 10],
        [-2,  1]])

In [ ]:
B_pt = torch.tensor([[-1,7],[10,8]])
B_pt

tensor([[-1,  7],
        [10,  8]])

In [ ]:
torch.mul(A_pt,B_pt)

tensor([[-25,  70],
        [-20,   8]])

In [ ]:
w = np.array([-1,2,-2])
x = np.array([5,10,0])
np.dot(w,x)

15

In [3]:
import torch
w = torch.tensor([-1,2,-2],dtype=torch.float32)
x= torch.tensor([5,10,0],dtype=torch.float32)
torch.dot(w,x)

tensor(15.)