In [1]:
import numpy as np
import torch

In [3]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [4]:
np.linalg.norm(X)

5.477225575051661

In [8]:
X_pt = torch.tensor([[1,2],[3,4]],dtype=torch.float16) #Norms and dot products in pytorch and Tensorflow require float values
X_pt

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)

In [9]:
torch.norm(X_pt) 

tensor(5.4766, dtype=torch.float16)

In [10]:
#---------MATRIX MULTIPLICATION----------------# 
A= np.array([[3,4],[5,6],[7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [11]:
B =np.array([1,2])
B

array([1, 2])

In [12]:
np.dot(A,B)

array([11, 17, 23])

In [19]:
A_pt = torch.tensor([[3,4],[5,6],[7,8]])
B_pt = torch.tensor([1,2])
torch.matmul(A_pt,B_pt)

tensor([11, 17, 23])

In [23]:
A2 = np.array([[3,4],[5,6],[7,8]])
B2 =np.array([[1,9],[2,0]])

In [21]:
A1_pt = torch.tensor([[3,4],[5,6],[7,8]])
B1_pt = torch.tensor([[1,9],[2,0]])
torch.matmul(A1_pt,B1_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [27]:
A2_pt = torch.from_numpy(A2) #Copies the array from numpy
B2_pt = torch.from_numpy(B2)
display(A2_pt,B2_pt,torch.matmul(A2_pt,B2_pt))

tensor([[3, 4],
        [5, 6],
        [7, 8]])

tensor([[1, 9],
        [2, 0]])

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [30]:
sym_mat = torch.tensor([[0,1,2],[1,7,8],[2,8,9]])
display(sym_mat,sym_mat.T)

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

In [32]:
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
display(I)
v_pt = torch.tensor([3,2,4])
display(v_pt)
display(torch.matmul(v_pt,I))

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

tensor([3, 2, 4])

tensor([3, 2, 4])

In [36]:
torch.matmul(torch.tensor([[0,1,2],[3,4,5],[6,7,8]]), torch.tensor([-1,1,-2]))

tensor([ -3,  -9, -15])

In [34]:
torch.matmul(torch.tensor([[1,0,0],[0,1,0],[0,0,1]]), torch.tensor([-1,1,-2]))

tensor([-1,  1, -2])

In [37]:
torch.matmul(torch.tensor([[0,1,2],[3,4,5],[6,7,8]]), torch.tensor([[-1,0],[1,1],[-2,2]]))

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])

In [43]:
#--------------------MATRIX INVERSION--------------------#
#To solve system of linear equations 
# numpy - np.linalg.inv(X)
torch.matmul(torch.inverse(torch.tensor([[4,2],[-5,-3.]])),torch.tensor([4,-7.])) #inverse requires float 


tensor([-1.,  4.])

In [44]:
Z = np.array([[-4,1],[-8,2]])
Z

array([[-4,  1],
       [-8,  2]])

In [46]:
#Zinv = np.linalg.inv(Z) - Error because of singular matrix

In [54]:
#M = torch.tensor([[-4,1],[-8,2],[5,6]], dtype=torch.float16)
#display(M)
#torch.inverse(M)  #Error because of non sqaure matrix


In [62]:
I3 = torch.tensor([[1,0,0],[0,1,0],[0,0,1.]])
display(torch.dot(I3[0,:],I3[1,:]))
display(torch.dot(I3[1,:],I3[2,:]))  #Dot products of any two rows of orthogonal matrix is 0. 

tensor(0.)

tensor(0.)

In [61]:
display(torch.norm(I3[0,:])) #Norm of every column of orthogonal matrix is 1.
display(torch.norm(I3[1,:]))
display(torch.norm(I3[2,:]))

tensor(1.)

tensor(1.)

tensor(1.)

In [67]:
K = torch.tensor([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])
display(K)
display(torch.dot(K[0,:],K[1,:]))
display(torch.dot(K[1,:],K[2,:]))  #Dot products of any two rows of orthogonal matrix is 0. 

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

tensor(0.)

tensor(0.)

In [68]:
display(torch.norm(K[0,:])) #Norm of every column of orthogonal matrix is 1.
display(torch.norm(K[1,:]))
display(torch.norm(K[2,:]))

tensor(1.)

tensor(1.)

tensor(1.)

In [69]:
torch.matmul(K.T, K)

tensor([[ 1.0000e+00, -3.3114e-09,  3.3114e-09],
        [-3.3114e-09,  1.0000e+00,  6.6227e-09],
        [ 3.3114e-09,  6.6227e-09,  1.0000e+00]])