<a href="https://colab.research.google.com/github/pythongeek0408/baby_steps_python/blob/main/Tensor_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
A = np.array([[25,2],[5,26],[3,7]])
A

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
A.sum() 

68

In [ ]:
X_pt = torch.tensor([[25,2],[5,26],[3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
torch.sum(X_pt)

tensor(68)

In [ ]:
X_tf = X_pt
X_tf

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int64, numpy=68>

In [ ]:
A.sum(axis = 1) #Summing all columns

array([27, 31, 10])

In [ ]:
A.sum(axis=0) #Summing all rows

array([33, 35])

In [ ]:
torch.sum(X_pt,0)

tensor([33, 35])

In [ ]:
torch.prod(X_pt,1) 

tensor([ 50, 130,  21])